export const products = [
    {
      id: 1,
      name: "Baju Sablon Karakter Anime Jepang L/XL",
      category: "Baju",
      price: 30,
      image: "/images/products/baju1.png",
      isCart: false,
      description: "Baju sablon karakter anime khas Jepang. baju lengan pendek dengan warna yang tersedia dan bervariasi. Desain yang tersedia,Terpopuler yaitu karakter Anime OnePiece,Naruto,JujutsuKaisen dan masih banyak lagi",
    },
    {
      id: 2,
      name: "Pensil Kayu FaberCastell 2B ,1 package",
      category: "Alat Tulis",
      price: 1,
      image: "/images/products/pensil.png",
      isCart: false,
      description: "Pensil Kayu Faber Castell 2B, 1 package 8 pieces. Pensil kayu kualitas sempurna dengan warna hitam pekat cocok untuk kebutuhan sekolah",
    },
    {
      id: 3,
      name: "Baju Sablon Khas Programmer Pria L/XL",
      category: "Baju",
      price: 28,
      image: "/images/products/baju2.png",
      isCart: false,
      description: "Baju sablon dengan desain yang khas untuk para Programmer dan IT. warna baju bervariasi, baju lengan pendek dengan ukuran L & XL. Cocok digunakan untuk remaja pria",
    },
    {
      id: 4,
      name: "Pulpen AE7, 1 package",
      category: "Alat Tulis",
      price: 1,
      image: "/images/products/pen.png",
      isCart: false,
      description: "Pulpen Sekolah dengan merk AE7.Pembelian 1 package yang berisi 6 pieces. Cocok dipakai untuk menulis dan menggambar, tersedia dengan 3 warna berbeda (hitam, biru, merah)",
    },
    {
      id: 5,
      name: "Formal School Socks",
      category: "Sepatu",
      price: 2,
      image: "/images/products/kaosKaki.png",
      isCart: false,
      description: "Kaos Kaki formal untuk anak sekolah, warna putih dan bawahan hitam",
    },
    {
      id: 6,
      name: "Kaos/Baju Polos L/XL",
      category: "Baju",
      price: 10,
      image: "/images/products/polos.png",
      isCart: false,
      description: "Kaos/baju polos cocok untuk pria dan wanita. kaos/baju polos dengan ukuran L & XL, ukuran remaja dan warna yang bervariasai, mulai dari hitam, putih dan banyak lagi. bahan lembut dan sejuk cocok pula dipakai untuk bersantai",
    },
  ];

  